---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: httpdserver
  name: httpdserver
  namespace: cloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpdserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: httpdserver
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: httpdserver
                topologyKey: kubernetes.io/hostname
      containers:
        - env:
           - name: VERSION
             value: VERSION
          image: 'chenzmin/httpdserver'
          imagePullPolicy: IfNotPresent
          name: httpdserver
          readinessProbe:
            httpGet:
              path: /heathz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /heathz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 1
            periodSeconds: 3
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 2Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 60
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: httpdserver
  name: httpdserver
  namespace: cloud
spec:
  ports:
    - name: consul-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: httpdserver
  sessionAffinity: None
  type: ClusterIP